# Generated by Django 4.2.5 on 2023-09-11 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_doctor_is_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='picture',
            field=models.ImageField(default=1, upload_to='pictures/'),
            preserve_default=False,
        ),
    ]
