# Generated by Django 4.2.5 on 2023-09-16 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_user_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='phone_number',
        ),
    ]
