# Generated by Django 4.2.5 on 2023-09-27 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_remove_user_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='doc',
            fields=[
            ],
            options={
                'ordering': ('is_active',),
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('api.user',),
        ),
    ]
