# Generated by Django 4.2.5 on 2023-09-27 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_doc'),
    ]

    operations = [
        migrations.DeleteModel(
            name='doc',
        ),
    ]
