# Generated by Django 4.2.5 on 2023-09-27 09:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_delete_doc'),
    ]

    operations = [
        migrations.CreateModel(
            name='docUser',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('name', models.CharField(max_length=120)),
            ],
            options={
                'abstract': False,
            },
            bases=('api.user',),
        ),
    ]
