# Generated by Django 4.2.5 on 2023-09-27 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_docuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='docUser',
        ),
    ]
